repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: check-json
      - id: name-tests-test
      - id: fix-encoding-pragma
        args: [ '--remove' ]
      - id: no-commit-to-branch
        args: [ --branch, staging ]
      - id: mixed-line-ending
        auto-correct: true
-   repo: https://github.com/hhatto/autopep8
    rev: v2.1.1
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
